### ISSUE TITLE
Context does not work after latest nvim nighly update

### ISSUE THREAD

**Issue by saumyajyoti** [romgrk/nvim-treesitter-context#51] opened 2021-06-05 09:54 UTC
It gives error Cannot resolve symbol curwin_col_off

**Comment by romgrk** [comment] 2021-06-05 17:01
Can't reproduce, can you try again from a fresh git clone? If it persists, please provide more details on your setup.

**Comment by saumyajyoti** [comment] 2021-06-06 04:47
Issue persists after reinstall.

Error detected while processing CursorMoved Autocommands for "*":
E5108: Error executing lua ...ugged\nvim-treesitter-context\lua\treesitter-context.lua:212: Vim(lua):E5108: Error executing lua ...ugged\nvim-treesitter-context\lua\treesitter-context.lua:152: cannot resolve symbol 'curwin_col_off': The specified procedure could not be found.

--- NVIM details -----

NVIM v0.5.0-dev+1372-g056c464e8
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-729

**Comment by romgrk** [comment] 2021-06-06 19:10
I don't have a windows copy available so I can't debug. Can you `git bisect` to find the commit that introduced the issue? What's the last working commit? Does reverting to a previously known to work commit fix the issue?

**Comment by saumyajyoti** [comment] 2021-06-07 04:43
It was working on week back. I'll try to go back to older version of the nvim and the plugins and check.

**Comment by ggandor** [comment] 2021-06-29 21:06
I can reproduce on Windows with the latest nightly.

**Comment by ggandor** [comment] 2021-07-15 20:05
Related: https://github.com/neovim/neovim/issues/15063

**Comment by romgrk** [comment] 2021-08-02 04:27
Not sure what's the best solution. We could open an issue upstream for the horizontal offset or fallback to scripted implementation for windows. Btw this was the result of a change in neovim right? It used to work on windows?

**Comment by zeertzjq** [comment] 2021-12-04 07:40
Note: <https://github.com/neovim/neovim/pull/16377> introduced a feature that can eliminate the need for LuaJIT FFI in this plugin.

**Comment by romgrk** [comment] 2022-01-08 23:04
Awesome, we should make use of that as soon as possible.

**Comment by romgrk** [comment] 2022-01-08 23:29
Closed by #83. Please re-open if it persists.

**Closed by romgrk** 2022-01-08 23:29 UTC
